### ISSUE TITLE
Blank Space on where the lights should show up

### ISSUE THREAD

**Issue by JustDaniMusic** [TakingFire/HueSaber#10]
**Describe the bug**

When i try to connect HueSaber to my bridge, It flashes no lights detected for a split second and then it shows a blank space. It does not say that it didn't found any lights. But it isn't showing lights either. I've had this earlier and the bug was fixed, but now its here again i think.

**To Reproduce**

Simply connect huesaber with a bridge, (If it is the same bug, then connect it to a bridge that includes white-only lights) and a blank space under the lights section will show.

**Additional context**

I've put a screenshot of the console here:

![image](https://user-images.githubusercontent.com/63183257/227760831-cbc5f1be-902a-46e1-b2fd-ac0fb6c180ed.png)

**Comment by TakingFire** [comment]
Oh yes, there's a chance I forgot to handle non-color lights again when I rewrote the application. Will patch soon!

**Comment by TakingFire** [comment]
This should now be fixed in [version 1.3.1](https://github.com/TakingFire/HueSaber/releases/tag/v1.3.1).
I'm also allowing HueSaber to send data to non-color lights this time, however I don't know how they'll respond.
Ideally, they should only change in brightness. If you give them a try, let me know what the results are!
