### ISSUE TITLE
Add Multiple Bridge Support

### ISSUE THREAD

**Issue by JustDaniMusic** [TakingFire/HueSaber#3]
**Describe your request**
When i try to connect to my bridge it picks up the first bridge it finds. However my lights are stored on the other bridge. So what now? So my suggestion is is if you try to find bridges and it finds multiple it will show a list including the bridge name and ip adress

**Additional context**
If you're unable to make the list you can also add a feature so you can put your bridge ip manually. But if you have mutliple bridges right now it results in an issue because there is now way around it.

**Comment by TakingFire** [comment]
This is indeed an important oversight, expect a patch in the next couple days!

**Comment by TakingFire** [comment]
This should be fixed in the [latest release](https://github.com/TakingFire/HueSaber/releases/tag/v1.1.1), following d1191e4.
In order to get your other bridge connected, simply use the `Remove Bridge` button in the Options menu.

![image](https://user-images.githubusercontent.com/38340654/149054669-8d7c5fe9-7b92-4e38-b2ed-cf56e7bee0c3.png)
