### ISSUE TITLE
Add suport of Open RGB

### ISSUE THREAD

**Issue by ThePinkUnicorn6** [TakingFire/HueSaber#7]
Having support to allow beatsaber lighting to be used with [Open RGB](https://gitlab.com/CalcProgrammer1/OpenRGB) would allow for many more devices to be supported. This would may be possible to implement using webhooks and Open RGB's [http hook plugin](https://gitlab.com/OpenRGBDevelopers/OpenRGBHttpHookPlugin) but might require the creation of a plugin just for this.

**Comment by TakingFire** [comment]
Admittedly, I'd forgotten to respond to this request until now. While support for a broad set of devices would be cool, OpenRGB is beyond the scope of this application as well as outside of performance and ecosystem constraints.

On the technical side, HueSaber processes effects internally, and streams continuously at around 30Hz. I can't support arbitrary devices as they would have to be able to handle that throughput, and also process data lossily in order to stay responsive.

HueSaber was built and is tested solely with Philips Hue in mind, and will likely remain that way. If another ecosystem *were* to be integrated in the future, it would be done very carefully and intentionally.
